import os
import json

def generate():
    a2e_dir = "a2e_core"
    js_path = os.path.join("playground", "py_source.js")
    os.makedirs("playground", exist_ok=True)
    
    files = [
        "__init__.py",
        "query_engine.py",
        "doc_store.py",
        "vector_store.py",
        "compiler.py",
        "operations.py",
        "engine.py"
    ]
    
    source_dict = {}
    for filename in files:
        filepath = os.path.join(a2e_dir, filename)
        if os.path.exists(filepath):
            with open(filepath, "r", encoding="utf-8") as f:
                source_dict[filename] = f.read()
                
    js_content = f"// Automatically generated by generate_py_source.py\nwindow.A2E_PY_SOURCE = {json.dumps(source_dict, ensure_ascii=False)};\n"
    
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(js_content)
        
    print(f"[OK] Generated {js_path} successfully containing {len(source_dict)} A2E core files!")

if __name__ == "__main__":
    generate()
